---
  - name: (CentOS) Update the system
    yum:
      name: '*'
      state: latest
    when: ansible_distribution  == 'CentOS'


  - name: (Ubuntu) Update DNS
    ansible.builtin.lineinfile:
      path: /etc/systemd/resolved.conf
      regexp: '^DNS '
      insertafter: '^#DNS='
      line: "DNS={{ dns_server }}"
    when: ansible_distribution  == 'Ubuntu'

  - name: (Ubuntu) server reboot
    reboot:
    when: ansible_distribution  == 'Ubuntu'


  - name: (Ubuntu) Wait 300 seconds for port 22 to become open 
    ansible.builtin.wait_for:
      port: 22
      delay: 10
    when: ansible_distribution  == 'Ubuntu'


  - name: (Ubuntu) Update the system
    apt:
      name: '*'
      state: latest
    when: ansible_distribution  == 'Ubuntu'

